---
- block:
  - name: ansible-zabbix-server | Install Zabbix 3.4 repository on CentOS 7
    yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
      state: present

  - name: ansible-zabbix-server | Install Zabbix Server Packages (PostgreSQL)
    yum:
      update_cache: yes
      name: "{{ item }}"
      state: present
    with_items:
      - zabbix-agent
      - zabbix-server-pgsql
      - zabbix-web-pgsql
      - python-psycopg2
      - fping
  when: ansible_distribution_major_version == "7"
